name: Continuous Integration
on: [push]

jobs:
  test dotnet:
    name: Build and test C#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install .NET
      uses: actions/setup-dotnet@v4
    - name: install C# dependencies
      run: dotnet restore
    - name: Build dotnet
      run: dotnet build --no-restore
    - name: Lint JS
      working-directory: DotnetTemplate.Web
      run: npm run lint
    - name: Test C#
      run: dotnet test --no-build

  test js:
    name: Build and test TypeScript
    steps:
    - uses: actions/checkout@v4
    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: DotnetTemplate.Web
    - name: install NPM dependencies
      working-directory: DotnetTemplate.Web
      run: npm ci
    - name: Build JS
      working-directory: DotnetTemplate.Web
      run: npm run build
    - name: Test JS
      working-directory: DotnetTemplate.Web
      run: npm test
