name: Continuous Integration
on: [push]

jobs:
  dotnet:
    name: Build and test C#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install .NET
      uses: actions/setup-dotnet@v4
    - name: install C# dependencies
      run: dotnet restore
    - name: Build dotnet
      run: dotnet build --no-restore
    - name: Test C#
      run: dotnet test --no-build

  js:
    name: Build and test TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
    - uses: actions/checkout@v4
    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: DotnetTemplate.Web
    - name: install NPM dependencies
      run: npm ci
    - name: Build JS
      run: npm run build
    - name: Lint JS
      run: npm run lint
    - name: Test JS
      run: npm test
